name: rick_and_morty_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  sqflite: ^2.4.2
  path: ^1.9.0
  provider: ^6.1.5+1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
  macos:
    generate: true
    image_path: "assets/app_logo.png"
  linux:
    generate: true
    image_path: "assets/app_logo.png"
